In [15]:
# Import Global & Machine Learning Libraries
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

from keras.preprocessing.image import ImageDataGenerator


In [16]:
train: ImageDataGenerator
test: ImageDataGenerator

In [18]:
train_generator = ImageDataGenerator(rescale=1/255.0)

train = train_generator.flow_from_directory(
    directory='../data/train/',
    target_size=(250, 250),
    color_mode='grayscale',
    class_mode='binary',
    batch_size=163,
)

test_generator = ImageDataGenerator(rescale=1/255.0)

test = test_generator.flow_from_directory(
    directory='../data/test/',
    target_size=(250, 250),
    color_mode='grayscale',
    class_mode='binary',
    batch_size=312,
)

Found 1000 images belonging to 2 classes.
Found 624 images belonging to 2 classes.


In [19]:
train_normal = train[0]
train_pneumonia = train[1]

In [20]:
# for reshape : len(train[0][1]) == btach_size
train_normal_data = train_normal[0].reshape(len(train_normal[1]), -1) 
train_normal_target = train_normal[1]
train_pneumonia_data = train_pneumonia[0].reshape(len(train_pneumonia[1]), -1)
train_pneumonia_target = train_pneumonia[1]

train_pneumonia_data.shape

(163, 62500)

In [21]:
train_data = [*train_normal_data, *train_pneumonia_data]
train_target = [*train_normal_target, *train_pneumonia_target]

In [22]:
test_normal = test[0]
test_pneumonia = test[1]

In [23]:
test_normal_data = test_normal[0].reshape(len(test_normal[1]), -1)
test_normal_target = test_normal[1]
test_pneumonia_data = test_pneumonia[0].reshape(len(test_pneumonia[1]), -1)
test_pneumonia_target = test_pneumonia[1]

test_pneumonia_data.shape

(312, 62500)

In [24]:
test_data = [*test_normal_data, *test_pneumonia_data]
test_target = [*test_normal_target, *test_pneumonia_target]

In [25]:
# Model Creation
model=LogisticRegression(max_iter=6000)

# Model Training
model.fit(train_data,train_target)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=6000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
# Predict y_pred
pred_target = model.predict(test_data)
pred_target

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 1.

In [27]:
# Compare Prevision with Real Values
comp=pd.DataFrame(pred_target, test_target)
pred_target

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1.,
       1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1.,
       1., 0., 0., 0., 1.

In [28]:
# Model Accuracy
print("La précision du modèle:", accuracy_score(test_target, pred_target))

La précision du modèle: 0.8221153846153846


In [29]:
# Confusion Matrix Visualisation
print(confusion_matrix(test_target, pred_target))

# tpos, fneg, fpos, tneg = confusion_matrix(test_target, pred_target).ravel()
# tpos, fneg, fpos, tneg

[[135  99]
 [ 12 378]]
